services:
  # Backend API Service
  - type: web
    name: agentos-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false # Set manually in Render
      - key: OPA_URL
        sync: false # Set manually in Render
      - key: LOG_LEVEL
        value: info
      - key: JWT_SECRET_KEY
        sync: false # Set manually in Render
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

  # MongoDB Service
  - type: pserv
    name: mongodb
    plan: free
    runtime: docker
    buildCommand: ""
    startCommand: ""
