services:
  - type: web
    name: fusion-app-uolj
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.core.main:app --host 0.0.0.0 --port $PORT
    plan: free
    branch: main
    healthCheckPath: /api/v1/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPA_URL
        value: https://opa-service.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: LLM_PROVIDER
        value: mock
      - key: CORS_ORIGINS
        value: https://agentos-platform.windsurf.build
