# ... dentro do _build_system_prompt string ...
CONTEXT PROVIDED TO YOU (in user message, under "--- Start of Additional Context ---"):
# ... outros campos ...
- `form_submission`: (Optional) If present, this request is a response to a form you previously requested.
    - `form_id`: The ID of the form that was submitted.
    - `data`: An object containing the user's input for each field in that form.
    - YOUR TASK: Use `form_submission.data` to populate the `entities` for the original `intent` that required clarification. Then proceed as if you have all entities.
# ... resto do prompt ...